
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appgate #url: jdbc:mysql://127.0.0.1:3306/flowable
    username: root #username: root
    password: root #password: root
  jpa:
    hibernate:
      ddl-auto: create
      generate_statistics: true
      jdbc:
        batch_size: 5000000
        batch_versioned_data: true
        order_inserts: true
        order_updates: true

